services:
  app:
    image: ghcr.io/imirjar/poliglotim-app:v0.4.1
    # build:
    #   context: /Users/artemzadorov/development/flutter/examples/poliglotim
    #   dockerfile: Dockerfile
    # image: poliglotim-app:local
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - apisix
    networks:
      - apisix-network

  site:
    image: ghcr.io/imirjar/poliglotim-site:latest
    restart: always
    ports:
      - "8000:80"
    networks:
      - apisix-network

  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "80:9080/tcp"
      - "443:9443/tcp"
    networks:
      - apisix-network
    depends_on:
      - keycloak
      - courses
      # - site

  courses:
    image: ghcr.io/imirjar/poliglotim-api:latest
    container_name: poliglotim-api
    restart: unless-stopped
    environment:
      PORT: "6060"
      DB_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    # expose:
    #   - "6060"
    ports:
      - "6060:6060"
    networks:
      - apisix-network
    depends_on:
      postgres:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: http://auth.dev.plyglo.com
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes:ro
    networks:
      - apisix-network

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge
