services:
  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "443:9443/tcp"
    networks:
      - apisix-network
    depends_on:
      - keycloak
      - courses

  courses:
    image: ghcr.io/imirjar/poliglotim-api:latest
    container_name: poliglotim-api
    restart: unless-stopped
    environment:
      PORT: "6060"
      DB_CONN: ${DB_CONN}
    expose:
      - "6060"
    networks:
      - apisix-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak
    restart: unless-stopped
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    networks:
      - apisix-network

networks:
  apisix-network:
    driver: bridge

volumes:
  etcd_data:
    driver: local
