http:
  routers:
    site:
      rule: Host(`plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: caddy

    app:
      rule: Host(`study.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: caddy

    api:
      rule: Host(`api.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: api

    auth:
      rule: Host(`auth.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: auth

  services:

    caddy:
      loadBalancer:
        servers:
          - url: http://caddy:80

    api:
      loadBalancer:
        servers:
          - url: http://courses:6060

    auth:
      loadBalancer:
        servers:
          - url: http://keycloak:8080
