http:
  routers:
    site:
      rule: Host(`plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: site

    app:
      rule: Host(`study.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: app

    api:
      rule: Host(`api.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: api

    auth:
      rule: Host(`auth.plyglo.com`)
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: auth

  services:
    site:
      loadBalancer:
        servers:
          - url: http://site:80

    app:
      loadBalancer:
        servers:
          - url: http://app:80

    api:
      loadBalancer:
        servers:
          - url: http://courses:6060

    auth:
      loadBalancer:
        servers:
          - url: http://keycloak:8080
