apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config
  namespace: poliglotim
data:
  config.yaml: |
    apisix:
      node_listen: 9080
      enable_ipv6: false
      config_center: yaml

    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml
  apisix.yaml: |
    routes:
      - id: courses-route
        uri: /courses
        upstream:
          pass_host: node
          nodes:
            "courses:6060": 1
          type: roundrobin

      - id: keycloak-realms
        uri: /realms/*
        upstream:
          nodes:
            "keycloak:8080": 1
          type: roundrobin

      - id: keycloak-resources
        uri: /resources/*
        upstream:
          nodes:
            "keycloak:8080": 1
          type: roundrobin

      - id: protected-courses-content
        uris:
          - /chapters
          - /chapters/*
          - /lessons
          - /lessons/*
        upstream:
          pass_host: node
          nodes:
            "courses:6060": 1
          type: roundrobin
        plugins:
          openid-connect:
            client_id: apisix
            client_secret: __APISIX_CLIENT_SECRET__
            discovery: https://api.example.com/realms/study/.well-known/openid-configuration
            bearer_only: true
            realm: "study"
            scope: openid profile email
            unauth_action: "deny"

    #END
