apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-template.yaml
  - apisix-configmap.yaml
  - keycloak-realm-configmap.yaml
  - courses.yaml
  - keycloak.yaml
  - apisix.yaml
