apiVersion: v1
kind: Secret
metadata:
  name: poliglotim-secrets
  namespace: poliglotim
type: Opaque
stringData:
  DB_CONN: "postgresql://user:password@postgres.example.com:5432/courses"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "change-me"
  APISIX_CLIENT_SECRET: "apisix-secret"
  APISIX_SESSION_SECRET: "replace-with-64-byte-random-hex"
